feat: added uniq hash in kubeconfig_path
getkuby/kuby-digitalocean pull request #3
Opened 2020-10-30 10:24 UTC by pandwoter

Hello this is the fix for following issue (https://github.com/getkuby/kuby-digitalocean/issues/2)
also, it depends on this PR (https://github.com/getkuby/kuby-core/pull/43)

2020-10-30 11:45 UTC, pandwoter commented
I'm not really sure why but on my local setup ```config.access_token + config.cluster_id``` says that config.access_token and config.cluster_id is nil (but they are provided in kuby.rb). 

So can you please point me when actually ```configure``` method of provider is called and is there a situations when Provider is called without executing a ```configure``` method?

2020-10-30 17:38 UTC, camertron requested changes

2020-10-30 17:38 UTC, camertron commented on lib/kuby/digitalocean/provider.rb
> +          "-#{generate_hash(config.access_token + config.cluster_id)}" \
Can we move `generate_hash` into this class? Defining it in the superclass means 1) we'd have to make kuby-digitalocean depend on a specific version of kuby-core, and 2) we're saying the hash function needs to be the same across all providers. All we really care about is the uniqueness of the path on disk. The mechanism that provides that unique path can (and should IMHO) be provider-independent.

2020-10-30 17:40 UTC, camertron commented
@pandwoter hmm I'm not sure why that would happen either. How are you testing gem changes locally? The `configure` method is called [here](https://github.com/getkuby/kuby-core/blob/c56945db98a68bc07fd93e9b7b75d98ba2deae0a/lib/kuby/kubernetes/spec.rb#L37).

2020-10-31 12:27 UTC, pandwoter commented
Done!

2020-10-31 22:35 UTC, camertron commented
@pandwoter ok, this looks awesome! I did a little testing and encountered the same `nil`s for cluster ID and access token. It happens because, unfortunately, the `kubeconfig_path` method is called before Kuby has been fully initialized. Fortunately there's a fairly easy workaround we can use to call `kubeconfig_path` a little later in the process. I'll merge this PR then add in the fix and publish a new release.

2020-11-01 17:08 UTC, merged

2020-11-01 17:17 UTC, camertron commented
Published as v0.4.3, thanks again!